# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_mdAddrPythonWrapper')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_mdAddrPythonWrapper')
    _mdAddrPythonWrapper = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mdAddrPythonWrapper', [dirname(__file__)])
        except ImportError:
            import _mdAddrPythonWrapper
            return _mdAddrPythonWrapper
        try:
            _mod = imp.load_module('_mdAddrPythonWrapper', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _mdAddrPythonWrapper = swig_import_helper()
    del swig_import_helper
else:
    import _mdAddrPythonWrapper
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class mdAddr(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdAddr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdAddr, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdAddr_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdAddr_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdAddr_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdAddr_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdAddr_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdAddr_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdAddr_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdAddr_Local
    Remote = _mdAddrPythonWrapper.mdAddr_Remote
    Auto = _mdAddrPythonWrapper.mdAddr_Auto
    On = _mdAddrPythonWrapper.mdAddr_On
    Off = _mdAddrPythonWrapper.mdAddr_Off
    ShortFormat = _mdAddrPythonWrapper.mdAddr_ShortFormat
    LongFormat = _mdAddrPythonWrapper.mdAddr_LongFormat
    AutoFormat = _mdAddrPythonWrapper.mdAddr_AutoFormat
    ParseSuite = _mdAddrPythonWrapper.mdAddr_ParseSuite
    CombineSuite = _mdAddrPythonWrapper.mdAddr_CombineSuite
    ConvertAlias = _mdAddrPythonWrapper.mdAddr_ConvertAlias
    PreserveAlias = _mdAddrPythonWrapper.mdAddr_PreserveAlias
    AutoCompleteSingleSuite = _mdAddrPythonWrapper.mdAddr_AutoCompleteSingleSuite
    AutoCompleteRangedSuite = _mdAddrPythonWrapper.mdAddr_AutoCompleteRangedSuite
    AutoCompletePlaceHolderSuite = _mdAddrPythonWrapper.mdAddr_AutoCompletePlaceHolderSuite
    AutoCompleteNoSuite = _mdAddrPythonWrapper.mdAddr_AutoCompleteNoSuite
    ResultCodeDescriptionLong = _mdAddrPythonWrapper.mdAddr_ResultCodeDescriptionLong
    ResultCodeDescriptionShort = _mdAddrPythonWrapper.mdAddr_ResultCodeDescriptionShort
    MailboxNone = _mdAddrPythonWrapper.mdAddr_MailboxNone
    MailboxExpress = _mdAddrPythonWrapper.mdAddr_MailboxExpress
    MailboxPremium = _mdAddrPythonWrapper.mdAddr_MailboxPremium

    def __init__(self):
        this = _mdAddrPythonWrapper.new_mdAddr()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdAddr
    __del__ = lambda self: None

    def Initialize(self, arg2, arg3, arg4):
        return _mdAddrPythonWrapper.mdAddr_Initialize(self, arg2, arg3, arg4)

    def InitializeDataFiles(self):
        return _mdAddrPythonWrapper.mdAddr_InitializeDataFiles(self)

    def GetInitializeErrorString(self):
        return _mdAddrPythonWrapper.mdAddr_GetInitializeErrorString(self)

    def SetLicenseString(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetLicenseString(self, arg2)

    def GetBuildNumber(self):
        return _mdAddrPythonWrapper.mdAddr_GetBuildNumber(self)

    def GetDatabaseDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetDatabaseDate(self)

    def GetExpirationDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetExpirationDate(self)

    def GetLicenseExpirationDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetLicenseExpirationDate(self)

    def GetCanadianDatabaseDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetCanadianDatabaseDate(self)

    def GetCanadianExpirationDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetCanadianExpirationDate(self)

    def SetPathToUSFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToUSFiles(self, arg2)

    def SetPathToCanadaFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToCanadaFiles(self, arg2)

    def SetPathToDPVDataFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToDPVDataFiles(self, arg2)

    def SetPathToLACSLinkDataFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToLACSLinkDataFiles(self, arg2)

    def SetPathToSuiteLinkDataFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToSuiteLinkDataFiles(self, arg2)

    def SetPathToSuiteFinderDataFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToSuiteFinderDataFiles(self, arg2)

    def SetPathToRBDIFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToRBDIFiles(self, arg2)

    def GetRBDIDatabaseDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetRBDIDatabaseDate(self)

    def SetPathToAddrKeyDataFiles(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPathToAddrKeyDataFiles(self, arg2)

    def ClearProperties(self):
        return _mdAddrPythonWrapper.mdAddr_ClearProperties(self)

    def ResetDPV(self):
        return _mdAddrPythonWrapper.mdAddr_ResetDPV(self)

    def SetCASSEnable(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetCASSEnable(self, arg2)

    def SetUseUSPSPreferredCityNames(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetUseUSPSPreferredCityNames(self, arg2)

    def SetDiacritics(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetDiacritics(self, arg2)

    def GetStatusCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetStatusCode(self)

    def GetErrorCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetErrorCode(self)

    def GetErrorString(self):
        return _mdAddrPythonWrapper.mdAddr_GetErrorString(self)

    def GetResults(self):
        return _mdAddrPythonWrapper.mdAddr_GetResults(self)

    def GetResultCodeDescription(self, *args):
        return _mdAddrPythonWrapper.mdAddr_GetResultCodeDescription(self, *args)

    def SetPS3553_B1_ProcessorName(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_B1_ProcessorName(self, arg2)

    def SetPS3553_B4_ListName(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_B4_ListName(self, arg2)

    def SetPS3553_D3_Name(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Name(self, arg2)

    def SetPS3553_D3_Company(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Company(self, arg2)

    def SetPS3553_D3_Address(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Address(self, arg2)

    def SetPS3553_D3_City(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_City(self, arg2)

    def SetPS3553_D3_State(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_State(self, arg2)

    def SetPS3553_D3_ZIP(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPS3553_D3_ZIP(self, arg2)

    def GetFormPS3553(self):
        return _mdAddrPythonWrapper.mdAddr_GetFormPS3553(self)

    def SaveFormPS3553(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SaveFormPS3553(self, arg2)

    def ResetFormPS3553(self):
        return _mdAddrPythonWrapper.mdAddr_ResetFormPS3553(self)

    def ResetFormPS3553Counter(self):
        return _mdAddrPythonWrapper.mdAddr_ResetFormPS3553Counter(self)

    def SetStandardizationType(self, mode):
        return _mdAddrPythonWrapper.mdAddr_SetStandardizationType(self, mode)

    def SetSuiteParseMode(self, mode):
        return _mdAddrPythonWrapper.mdAddr_SetSuiteParseMode(self, mode)

    def SetAliasMode(self, mode):
        return _mdAddrPythonWrapper.mdAddr_SetAliasMode(self, mode)

    def GetFormSOA(self):
        return _mdAddrPythonWrapper.mdAddr_GetFormSOA(self)

    def SaveFormSOA(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SaveFormSOA(self, arg2)

    def ResetFormSOA(self):
        return _mdAddrPythonWrapper.mdAddr_ResetFormSOA(self)

    def SetSOACustomerInfo(self, customerName, customerAddress):
        return _mdAddrPythonWrapper.mdAddr_SetSOACustomerInfo(self, customerName, customerAddress)

    def SetSOACPCNumber(self, CPCNumber):
        return _mdAddrPythonWrapper.mdAddr_SetSOACPCNumber(self, CPCNumber)

    def GetSOACustomerInfo(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOACustomerInfo(self)

    def GetSOACPCNumber(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOACPCNumber(self)

    def GetSOATotalRecords(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOATotalRecords(self)

    def GetSOAAAPercentage(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOAAAPercentage(self)

    def GetSOAAAExpiryDate(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOAAAExpiryDate(self)

    def GetSOASoftwareInfo(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOASoftwareInfo(self)

    def GetSOAErrorString(self):
        return _mdAddrPythonWrapper.mdAddr_GetSOAErrorString(self)

    def SetCompany(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetCompany(self, arg2)

    def SetLastName(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetLastName(self, arg2)

    def SetAddress(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetAddress(self, arg2)

    def SetAddress2(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetAddress2(self, arg2)

    def SetLastLine(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetLastLine(self, arg2)

    def SetSuite(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetSuite(self, arg2)

    def SetCity(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetCity(self, arg2)

    def SetState(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetState(self, arg2)

    def SetZip(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetZip(self, arg2)

    def SetPlus4(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetPlus4(self, arg2)

    def SetUrbanization(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetUrbanization(self, arg2)

    def SetParsedAddressRange(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedAddressRange(self, arg2)

    def SetParsedPreDirection(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedPreDirection(self, arg2)

    def SetParsedStreetName(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedStreetName(self, arg2)

    def SetParsedSuffix(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedSuffix(self, arg2)

    def SetParsedPostDirection(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedPostDirection(self, arg2)

    def SetParsedSuiteName(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedSuiteName(self, arg2)

    def SetParsedSuiteRange(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedSuiteRange(self, arg2)

    def SetParsedRouteService(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedRouteService(self, arg2)

    def SetParsedLockBox(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedLockBox(self, arg2)

    def SetParsedDeliveryInstallation(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetParsedDeliveryInstallation(self, arg2)

    def SetCountryCode(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_SetCountryCode(self, arg2)

    def VerifyAddress(self):
        return _mdAddrPythonWrapper.mdAddr_VerifyAddress(self)

    def GetCompany(self):
        return _mdAddrPythonWrapper.mdAddr_GetCompany(self)

    def GetLastName(self):
        return _mdAddrPythonWrapper.mdAddr_GetLastName(self)

    def GetAddress(self):
        return _mdAddrPythonWrapper.mdAddr_GetAddress(self)

    def GetAddress2(self):
        return _mdAddrPythonWrapper.mdAddr_GetAddress2(self)

    def GetSuite(self):
        return _mdAddrPythonWrapper.mdAddr_GetSuite(self)

    def GetCity(self):
        return _mdAddrPythonWrapper.mdAddr_GetCity(self)

    def GetCityAbbreviation(self):
        return _mdAddrPythonWrapper.mdAddr_GetCityAbbreviation(self)

    def GetState(self):
        return _mdAddrPythonWrapper.mdAddr_GetState(self)

    def GetZip(self):
        return _mdAddrPythonWrapper.mdAddr_GetZip(self)

    def GetPlus4(self):
        return _mdAddrPythonWrapper.mdAddr_GetPlus4(self)

    def GetCarrierRoute(self):
        return _mdAddrPythonWrapper.mdAddr_GetCarrierRoute(self)

    def GetDeliveryPointCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetDeliveryPointCode(self)

    def GetDeliveryPointCheckDigit(self):
        return _mdAddrPythonWrapper.mdAddr_GetDeliveryPointCheckDigit(self)

    def GetCountyFips(self):
        return _mdAddrPythonWrapper.mdAddr_GetCountyFips(self)

    def GetCountyName(self):
        return _mdAddrPythonWrapper.mdAddr_GetCountyName(self)

    def GetAddressTypeCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetAddressTypeCode(self)

    def GetAddressTypeString(self):
        return _mdAddrPythonWrapper.mdAddr_GetAddressTypeString(self)

    def GetUrbanization(self):
        return _mdAddrPythonWrapper.mdAddr_GetUrbanization(self)

    def GetCongressionalDistrict(self):
        return _mdAddrPythonWrapper.mdAddr_GetCongressionalDistrict(self)

    def GetLACS(self):
        return _mdAddrPythonWrapper.mdAddr_GetLACS(self)

    def GetLACSLinkIndicator(self):
        return _mdAddrPythonWrapper.mdAddr_GetLACSLinkIndicator(self)

    def GetPrivateMailbox(self):
        return _mdAddrPythonWrapper.mdAddr_GetPrivateMailbox(self)

    def GetTimeZoneCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetTimeZoneCode(self)

    def GetTimeZone(self):
        return _mdAddrPythonWrapper.mdAddr_GetTimeZone(self)

    def GetMsa(self):
        return _mdAddrPythonWrapper.mdAddr_GetMsa(self)

    def GetPmsa(self):
        return _mdAddrPythonWrapper.mdAddr_GetPmsa(self)

    def GetDefaultFlagIndicator(self):
        return _mdAddrPythonWrapper.mdAddr_GetDefaultFlagIndicator(self)

    def GetSuiteStatus(self):
        return _mdAddrPythonWrapper.mdAddr_GetSuiteStatus(self)

    def GetEWSFlag(self):
        return _mdAddrPythonWrapper.mdAddr_GetEWSFlag(self)

    def GetCMRA(self):
        return _mdAddrPythonWrapper.mdAddr_GetCMRA(self)

    def GetDsfNoStats(self):
        return _mdAddrPythonWrapper.mdAddr_GetDsfNoStats(self)

    def GetDsfVacant(self):
        return _mdAddrPythonWrapper.mdAddr_GetDsfVacant(self)

    def GetDsfDNA(self):
        return _mdAddrPythonWrapper.mdAddr_GetDsfDNA(self)

    def GetCountryCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetCountryCode(self)

    def GetZipType(self):
        return _mdAddrPythonWrapper.mdAddr_GetZipType(self)

    def GetFalseTable(self):
        return _mdAddrPythonWrapper.mdAddr_GetFalseTable(self)

    def GetDPVFootnotes(self):
        return _mdAddrPythonWrapper.mdAddr_GetDPVFootnotes(self)

    def GetLACSLinkReturnCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetLACSLinkReturnCode(self)

    def GetSuiteLinkReturnCode(self):
        return _mdAddrPythonWrapper.mdAddr_GetSuiteLinkReturnCode(self)

    def GetRBDI(self):
        return _mdAddrPythonWrapper.mdAddr_GetRBDI(self)

    def GetELotNumber(self):
        return _mdAddrPythonWrapper.mdAddr_GetELotNumber(self)

    def GetELotOrder(self):
        return _mdAddrPythonWrapper.mdAddr_GetELotOrder(self)

    def GetAddressKey(self):
        return _mdAddrPythonWrapper.mdAddr_GetAddressKey(self)

    def GetMelissaAddressKey(self):
        return _mdAddrPythonWrapper.mdAddr_GetMelissaAddressKey(self)

    def GetMelissaAddressKeyBase(self):
        return _mdAddrPythonWrapper.mdAddr_GetMelissaAddressKeyBase(self)

    def FindSuggestion(self):
        return _mdAddrPythonWrapper.mdAddr_FindSuggestion(self)

    def FindSuggestionNext(self):
        return _mdAddrPythonWrapper.mdAddr_FindSuggestionNext(self)

    def GetPS3553_B6_TotalRecords(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_B6_TotalRecords(self)

    def GetPS3553_C1a_ZIP4Coded(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_C1a_ZIP4Coded(self)

    def GetPS3553_C1c_DPBCAssigned(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_C1c_DPBCAssigned(self)

    def GetPS3553_C1d_FiveDigitCoded(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_C1d_FiveDigitCoded(self)

    def GetPS3553_C1e_CRRTCoded(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_C1e_CRRTCoded(self)

    def GetPS3553_C1f_eLOTAssigned(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_C1f_eLOTAssigned(self)

    def GetPS3553_E_HighRiseDefault(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_HighRiseDefault(self)

    def GetPS3553_E_HighRiseExact(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_HighRiseExact(self)

    def GetPS3553_E_RuralRouteDefault(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_RuralRouteDefault(self)

    def GetPS3553_E_RuralRouteExact(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_RuralRouteExact(self)

    def GetZip4HRDefault(self):
        return _mdAddrPythonWrapper.mdAddr_GetZip4HRDefault(self)

    def GetZip4HRExact(self):
        return _mdAddrPythonWrapper.mdAddr_GetZip4HRExact(self)

    def GetZip4RRDefault(self):
        return _mdAddrPythonWrapper.mdAddr_GetZip4RRDefault(self)

    def GetZip4RRExact(self):
        return _mdAddrPythonWrapper.mdAddr_GetZip4RRExact(self)

    def GetPS3553_E_LACSCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_LACSCount(self)

    def GetPS3553_E_EWSCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_EWSCount(self)

    def GetPS3553_E_DPVCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_E_DPVCount(self)

    def GetPS3553_X_POBoxCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_POBoxCount(self)

    def GetPS3553_X_HCExactCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_HCExactCount(self)

    def GetPS3553_X_FirmCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_FirmCount(self)

    def GetPS3553_X_GenDeliveryCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_GenDeliveryCount(self)

    def GetPS3553_X_MilitaryZipCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_MilitaryZipCount(self)

    def GetPS3553_X_NonDeliveryCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_NonDeliveryCount(self)

    def GetPS3553_X_StreetCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_StreetCount(self)

    def GetPS3553_X_HCDefaultCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_HCDefaultCount(self)

    def GetPS3553_X_OtherCount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_OtherCount(self)

    def GetPS3553_X_LacsLinkCodeACount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCodeACount(self)

    def GetPS3553_X_LacsLinkCode00Count(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode00Count(self)

    def GetPS3553_X_LacsLinkCode14Count(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode14Count(self)

    def GetPS3553_X_LacsLinkCode92Count(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode92Count(self)

    def GetPS3553_X_LacsLinkCode09Count(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode09Count(self)

    def GetPS3553_X_SuiteLinkCodeACount(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_SuiteLinkCodeACount(self)

    def GetPS3553_X_SuiteLinkCode00Count(self):
        return _mdAddrPythonWrapper.mdAddr_GetPS3553_X_SuiteLinkCode00Count(self)

    def GetParsedAddressRange(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedAddressRange(self)

    def GetParsedPreDirection(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedPreDirection(self)

    def GetParsedStreetName(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedStreetName(self)

    def GetParsedSuffix(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedSuffix(self)

    def GetParsedPostDirection(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedPostDirection(self)

    def GetParsedSuiteName(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedSuiteName(self)

    def GetParsedSuiteRange(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedSuiteRange(self)

    def GetParsedPrivateMailboxName(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedPrivateMailboxName(self)

    def GetParsedPrivateMailboxNumber(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedPrivateMailboxNumber(self)

    def GetParsedGarbage(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedGarbage(self)

    def GetParsedRouteService(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedRouteService(self)

    def GetParsedLockBox(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedLockBox(self)

    def GetParsedDeliveryInstallation(self):
        return _mdAddrPythonWrapper.mdAddr_GetParsedDeliveryInstallation(self)

    def SetReserved(self, arg2, arg3):
        return _mdAddrPythonWrapper.mdAddr_SetReserved(self, arg2, arg3)

    def GetReserved(self, arg2):
        return _mdAddrPythonWrapper.mdAddr_GetReserved(self, arg2)
mdAddr_swigregister = _mdAddrPythonWrapper.mdAddr_swigregister
mdAddr_swigregister(mdAddr)

class mdParse(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdParse, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdParse, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdParse_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdParse_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdParse_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdParse_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdParse_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdParse_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdParse_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdParse_Local
    Remote = _mdAddrPythonWrapper.mdParse_Remote
    Auto = _mdAddrPythonWrapper.mdParse_Auto
    On = _mdAddrPythonWrapper.mdParse_On
    Off = _mdAddrPythonWrapper.mdParse_Off
    ShortFormat = _mdAddrPythonWrapper.mdParse_ShortFormat
    LongFormat = _mdAddrPythonWrapper.mdParse_LongFormat
    AutoFormat = _mdAddrPythonWrapper.mdParse_AutoFormat
    ParseSuite = _mdAddrPythonWrapper.mdParse_ParseSuite
    CombineSuite = _mdAddrPythonWrapper.mdParse_CombineSuite
    ConvertAlias = _mdAddrPythonWrapper.mdParse_ConvertAlias
    PreserveAlias = _mdAddrPythonWrapper.mdParse_PreserveAlias
    AutoCompleteSingleSuite = _mdAddrPythonWrapper.mdParse_AutoCompleteSingleSuite
    AutoCompleteRangedSuite = _mdAddrPythonWrapper.mdParse_AutoCompleteRangedSuite
    AutoCompletePlaceHolderSuite = _mdAddrPythonWrapper.mdParse_AutoCompletePlaceHolderSuite
    AutoCompleteNoSuite = _mdAddrPythonWrapper.mdParse_AutoCompleteNoSuite
    ResultCodeDescriptionLong = _mdAddrPythonWrapper.mdParse_ResultCodeDescriptionLong
    ResultCodeDescriptionShort = _mdAddrPythonWrapper.mdParse_ResultCodeDescriptionShort
    MailboxNone = _mdAddrPythonWrapper.mdParse_MailboxNone
    MailboxExpress = _mdAddrPythonWrapper.mdParse_MailboxExpress
    MailboxPremium = _mdAddrPythonWrapper.mdParse_MailboxPremium

    def __init__(self):
        this = _mdAddrPythonWrapper.new_mdParse()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdParse
    __del__ = lambda self: None

    def Initialize(self, arg2):
        return _mdAddrPythonWrapper.mdParse_Initialize(self, arg2)

    def GetBuildNumber(self):
        return _mdAddrPythonWrapper.mdParse_GetBuildNumber(self)

    def Parse(self, arg2):
        return _mdAddrPythonWrapper.mdParse_Parse(self, arg2)

    def ParseCanadian(self, arg2):
        return _mdAddrPythonWrapper.mdParse_ParseCanadian(self, arg2)

    def ParseNext(self):
        return _mdAddrPythonWrapper.mdParse_ParseNext(self)

    def LastLineParse(self, arg2):
        return _mdAddrPythonWrapper.mdParse_LastLineParse(self, arg2)

    def GetZip(self):
        return _mdAddrPythonWrapper.mdParse_GetZip(self)

    def GetPlus4(self):
        return _mdAddrPythonWrapper.mdParse_GetPlus4(self)

    def GetCity(self):
        return _mdAddrPythonWrapper.mdParse_GetCity(self)

    def GetState(self):
        return _mdAddrPythonWrapper.mdParse_GetState(self)

    def GetStreetName(self):
        return _mdAddrPythonWrapper.mdParse_GetStreetName(self)

    def GetRange(self):
        return _mdAddrPythonWrapper.mdParse_GetRange(self)

    def GetPreDirection(self):
        return _mdAddrPythonWrapper.mdParse_GetPreDirection(self)

    def GetPostDirection(self):
        return _mdAddrPythonWrapper.mdParse_GetPostDirection(self)

    def GetSuffix(self):
        return _mdAddrPythonWrapper.mdParse_GetSuffix(self)

    def GetSuiteName(self):
        return _mdAddrPythonWrapper.mdParse_GetSuiteName(self)

    def GetSuiteNumber(self):
        return _mdAddrPythonWrapper.mdParse_GetSuiteNumber(self)

    def GetPrivateMailboxNumber(self):
        return _mdAddrPythonWrapper.mdParse_GetPrivateMailboxNumber(self)

    def GetPrivateMailboxName(self):
        return _mdAddrPythonWrapper.mdParse_GetPrivateMailboxName(self)

    def GetGarbage(self):
        return _mdAddrPythonWrapper.mdParse_GetGarbage(self)

    def GetRouteService(self):
        return _mdAddrPythonWrapper.mdParse_GetRouteService(self)

    def GetLockBox(self):
        return _mdAddrPythonWrapper.mdParse_GetLockBox(self)

    def GetDeliveryInstallation(self):
        return _mdAddrPythonWrapper.mdParse_GetDeliveryInstallation(self)

    def ParseRule(self):
        return _mdAddrPythonWrapper.mdParse_ParseRule(self)
mdParse_swigregister = _mdAddrPythonWrapper.mdParse_swigregister
mdParse_swigregister(mdParse)

class mdStreet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdStreet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdStreet, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdStreet_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdStreet_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdStreet_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdStreet_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdStreet_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdStreet_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdStreet_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdStreet_Local
    Remote = _mdAddrPythonWrapper.mdStreet_Remote
    Auto = _mdAddrPythonWrapper.mdStreet_Auto
    On = _mdAddrPythonWrapper.mdStreet_On
    Off = _mdAddrPythonWrapper.mdStreet_Off
    ShortFormat = _mdAddrPythonWrapper.mdStreet_ShortFormat
    LongFormat = _mdAddrPythonWrapper.mdStreet_LongFormat
    AutoFormat = _mdAddrPythonWrapper.mdStreet_AutoFormat
    ParseSuite = _mdAddrPythonWrapper.mdStreet_ParseSuite
    CombineSuite = _mdAddrPythonWrapper.mdStreet_CombineSuite
    ConvertAlias = _mdAddrPythonWrapper.mdStreet_ConvertAlias
    PreserveAlias = _mdAddrPythonWrapper.mdStreet_PreserveAlias
    AutoCompleteSingleSuite = _mdAddrPythonWrapper.mdStreet_AutoCompleteSingleSuite
    AutoCompleteRangedSuite = _mdAddrPythonWrapper.mdStreet_AutoCompleteRangedSuite
    AutoCompletePlaceHolderSuite = _mdAddrPythonWrapper.mdStreet_AutoCompletePlaceHolderSuite
    AutoCompleteNoSuite = _mdAddrPythonWrapper.mdStreet_AutoCompleteNoSuite
    ResultCodeDescriptionLong = _mdAddrPythonWrapper.mdStreet_ResultCodeDescriptionLong
    ResultCodeDescriptionShort = _mdAddrPythonWrapper.mdStreet_ResultCodeDescriptionShort
    MailboxNone = _mdAddrPythonWrapper.mdStreet_MailboxNone
    MailboxExpress = _mdAddrPythonWrapper.mdStreet_MailboxExpress
    MailboxPremium = _mdAddrPythonWrapper.mdStreet_MailboxPremium

    def __init__(self):
        this = _mdAddrPythonWrapper.new_mdStreet()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdStreet
    __del__ = lambda self: None

    def Initialize(self, arg2, arg3, arg4):
        return _mdAddrPythonWrapper.mdStreet_Initialize(self, arg2, arg3, arg4)

    def GetInitializeErrorString(self):
        return _mdAddrPythonWrapper.mdStreet_GetInitializeErrorString(self)

    def GetDatabaseDate(self):
        return _mdAddrPythonWrapper.mdStreet_GetDatabaseDate(self)

    def GetBuildNumber(self):
        return _mdAddrPythonWrapper.mdStreet_GetBuildNumber(self)

    def SetLicenseString(self, arg2):
        return _mdAddrPythonWrapper.mdStreet_SetLicenseString(self, arg2)

    def GetLicenseExpirationDate(self):
        return _mdAddrPythonWrapper.mdStreet_GetLicenseExpirationDate(self)

    def FindStreet(self, arg2, arg3, arg4):
        return _mdAddrPythonWrapper.mdStreet_FindStreet(self, arg2, arg3, arg4)

    def FindStreetNext(self):
        return _mdAddrPythonWrapper.mdStreet_FindStreetNext(self)

    def IsAddressInRange(self, arg2, arg3, arg4):
        return _mdAddrPythonWrapper.mdStreet_IsAddressInRange(self, arg2, arg3, arg4)

    def IsAddressInRange2(self, arg2, arg3, arg4, arg5):
        return _mdAddrPythonWrapper.mdStreet_IsAddressInRange2(self, arg2, arg3, arg4, arg5)

    def GetAutoCompletion(self, arg2, arg3, arg4, arg5):
        return _mdAddrPythonWrapper.mdStreet_GetAutoCompletion(self, arg2, arg3, arg4, arg5)

    def ResetAutoCompletion(self):
        return _mdAddrPythonWrapper.mdStreet_ResetAutoCompletion(self)

    def GetBaseAlternateIndicator(self):
        return _mdAddrPythonWrapper.mdStreet_GetBaseAlternateIndicator(self)

    def GetLACSIndicator(self):
        return _mdAddrPythonWrapper.mdStreet_GetLACSIndicator(self)

    def GetUrbanizationCode(self):
        return _mdAddrPythonWrapper.mdStreet_GetUrbanizationCode(self)

    def GetUrbanizationName(self):
        return _mdAddrPythonWrapper.mdStreet_GetUrbanizationName(self)

    def GetLastLineNumber(self):
        return _mdAddrPythonWrapper.mdStreet_GetLastLineNumber(self)

    def GetAddressType(self):
        return _mdAddrPythonWrapper.mdStreet_GetAddressType(self)

    def GetCongressionalDistrict(self):
        return _mdAddrPythonWrapper.mdStreet_GetCongressionalDistrict(self)

    def GetCountyFips(self):
        return _mdAddrPythonWrapper.mdStreet_GetCountyFips(self)

    def GetCompany(self):
        return _mdAddrPythonWrapper.mdStreet_GetCompany(self)

    def GetCarrierRoute(self):
        return _mdAddrPythonWrapper.mdStreet_GetCarrierRoute(self)

    def GetZip(self):
        return _mdAddrPythonWrapper.mdStreet_GetZip(self)

    def GetDeliveryInstallation(self):
        return _mdAddrPythonWrapper.mdStreet_GetDeliveryInstallation(self)

    def GetPlus4High(self):
        return _mdAddrPythonWrapper.mdStreet_GetPlus4High(self)

    def GetPlus4Low(self):
        return _mdAddrPythonWrapper.mdStreet_GetPlus4Low(self)

    def GetSuiteRangeOddEven(self):
        return _mdAddrPythonWrapper.mdStreet_GetSuiteRangeOddEven(self)

    def GetSuiteRangeHigh(self):
        return _mdAddrPythonWrapper.mdStreet_GetSuiteRangeHigh(self)

    def GetSuiteRangeLow(self):
        return _mdAddrPythonWrapper.mdStreet_GetSuiteRangeLow(self)

    def GetSuiteName(self):
        return _mdAddrPythonWrapper.mdStreet_GetSuiteName(self)

    def GetPostDirection(self):
        return _mdAddrPythonWrapper.mdStreet_GetPostDirection(self)

    def GetSuffix(self):
        return _mdAddrPythonWrapper.mdStreet_GetSuffix(self)

    def GetStreetName(self):
        return _mdAddrPythonWrapper.mdStreet_GetStreetName(self)

    def GetPreDirection(self):
        return _mdAddrPythonWrapper.mdStreet_GetPreDirection(self)

    def GetPrimaryRangeOddEven(self):
        return _mdAddrPythonWrapper.mdStreet_GetPrimaryRangeOddEven(self)

    def GetPrimaryRangeHigh(self):
        return _mdAddrPythonWrapper.mdStreet_GetPrimaryRangeHigh(self)

    def GetPrimaryRangeLow(self):
        return _mdAddrPythonWrapper.mdStreet_GetPrimaryRangeLow(self)
mdStreet_swigregister = _mdAddrPythonWrapper.mdStreet_swigregister
mdStreet_swigregister(mdStreet)

class mdZip(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdZip, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdZip, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdZip_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdZip_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdZip_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdZip_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdZip_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdZip_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdZip_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdZip_Local
    Remote = _mdAddrPythonWrapper.mdZip_Remote
    Auto = _mdAddrPythonWrapper.mdZip_Auto
    On = _mdAddrPythonWrapper.mdZip_On
    Off = _mdAddrPythonWrapper.mdZip_Off
    ShortFormat = _mdAddrPythonWrapper.mdZip_ShortFormat
    LongFormat = _mdAddrPythonWrapper.mdZip_LongFormat
    AutoFormat = _mdAddrPythonWrapper.mdZip_AutoFormat
    ParseSuite = _mdAddrPythonWrapper.mdZip_ParseSuite
    CombineSuite = _mdAddrPythonWrapper.mdZip_CombineSuite
    ConvertAlias = _mdAddrPythonWrapper.mdZip_ConvertAlias
    PreserveAlias = _mdAddrPythonWrapper.mdZip_PreserveAlias
    AutoCompleteSingleSuite = _mdAddrPythonWrapper.mdZip_AutoCompleteSingleSuite
    AutoCompleteRangedSuite = _mdAddrPythonWrapper.mdZip_AutoCompleteRangedSuite
    AutoCompletePlaceHolderSuite = _mdAddrPythonWrapper.mdZip_AutoCompletePlaceHolderSuite
    AutoCompleteNoSuite = _mdAddrPythonWrapper.mdZip_AutoCompleteNoSuite
    ResultCodeDescriptionLong = _mdAddrPythonWrapper.mdZip_ResultCodeDescriptionLong
    ResultCodeDescriptionShort = _mdAddrPythonWrapper.mdZip_ResultCodeDescriptionShort
    MailboxNone = _mdAddrPythonWrapper.mdZip_MailboxNone
    MailboxExpress = _mdAddrPythonWrapper.mdZip_MailboxExpress
    MailboxPremium = _mdAddrPythonWrapper.mdZip_MailboxPremium

    def __init__(self):
        this = _mdAddrPythonWrapper.new_mdZip()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdZip
    __del__ = lambda self: None

    def Initialize(self, arg2, arg3, arg4):
        return _mdAddrPythonWrapper.mdZip_Initialize(self, arg2, arg3, arg4)

    def GetInitializeErrorString(self):
        return _mdAddrPythonWrapper.mdZip_GetInitializeErrorString(self)

    def GetDatabaseDate(self):
        return _mdAddrPythonWrapper.mdZip_GetDatabaseDate(self)

    def GetBuildNumber(self):
        return _mdAddrPythonWrapper.mdZip_GetBuildNumber(self)

    def SetLicenseString(self, arg2):
        return _mdAddrPythonWrapper.mdZip_SetLicenseString(self, arg2)

    def GetLicenseExpirationDate(self):
        return _mdAddrPythonWrapper.mdZip_GetLicenseExpirationDate(self)

    def FindZip(self, arg2, arg3):
        return _mdAddrPythonWrapper.mdZip_FindZip(self, arg2, arg3)

    def FindZipNext(self):
        return _mdAddrPythonWrapper.mdZip_FindZipNext(self)

    def FindZipInCity(self, arg2, arg3):
        return _mdAddrPythonWrapper.mdZip_FindZipInCity(self, arg2, arg3)

    def FindZipInCityNext(self):
        return _mdAddrPythonWrapper.mdZip_FindZipInCityNext(self)

    def FindCityInState(self, arg2, arg3):
        return _mdAddrPythonWrapper.mdZip_FindCityInState(self, arg2, arg3)

    def FindCityInStateNext(self):
        return _mdAddrPythonWrapper.mdZip_FindCityInStateNext(self)

    def ComputeDistance(self, arg2, arg3, arg4, arg5):
        return _mdAddrPythonWrapper.mdZip_ComputeDistance(self, arg2, arg3, arg4, arg5)

    def ComputeBearing(self, arg2, arg3, arg4, arg5):
        return _mdAddrPythonWrapper.mdZip_ComputeBearing(self, arg2, arg3, arg4, arg5)

    def GetCountyNameFromFips(self, arg2):
        return _mdAddrPythonWrapper.mdZip_GetCountyNameFromFips(self, arg2)

    def GetSCFArea(self, arg2, arg3, arg4, arg5, arg6):
        return _mdAddrPythonWrapper.mdZip_GetSCFArea(self, arg2, arg3, arg4, arg5, arg6)

    def GetZip(self):
        return _mdAddrPythonWrapper.mdZip_GetZip(self)

    def GetCity(self):
        return _mdAddrPythonWrapper.mdZip_GetCity(self)

    def GetCityAbbreviation(self):
        return _mdAddrPythonWrapper.mdZip_GetCityAbbreviation(self)

    def GetState(self):
        return _mdAddrPythonWrapper.mdZip_GetState(self)

    def GetZipType(self):
        return _mdAddrPythonWrapper.mdZip_GetZipType(self)

    def GetCountyName(self):
        return _mdAddrPythonWrapper.mdZip_GetCountyName(self)

    def GetCountyFips(self):
        return _mdAddrPythonWrapper.mdZip_GetCountyFips(self)

    def GetAreaCode(self):
        return _mdAddrPythonWrapper.mdZip_GetAreaCode(self)

    def GetLongitude(self):
        return _mdAddrPythonWrapper.mdZip_GetLongitude(self)

    def GetLatitude(self):
        return _mdAddrPythonWrapper.mdZip_GetLatitude(self)

    def GetTimeZone(self):
        return _mdAddrPythonWrapper.mdZip_GetTimeZone(self)

    def GetTimeZoneCode(self):
        return _mdAddrPythonWrapper.mdZip_GetTimeZoneCode(self)

    def GetMsa(self):
        return _mdAddrPythonWrapper.mdZip_GetMsa(self)

    def GetPmsa(self):
        return _mdAddrPythonWrapper.mdZip_GetPmsa(self)

    def GetFacilityCode(self):
        return _mdAddrPythonWrapper.mdZip_GetFacilityCode(self)

    def GetLastLineIndicator(self):
        return _mdAddrPythonWrapper.mdZip_GetLastLineIndicator(self)

    def GetLastLineNumber(self):
        return _mdAddrPythonWrapper.mdZip_GetLastLineNumber(self)

    def GetPreferredLastLineNumber(self):
        return _mdAddrPythonWrapper.mdZip_GetPreferredLastLineNumber(self)

    def GetAutomation(self):
        return _mdAddrPythonWrapper.mdZip_GetAutomation(self)

    def GetFinanceNumber(self):
        return _mdAddrPythonWrapper.mdZip_GetFinanceNumber(self)
mdZip_swigregister = _mdAddrPythonWrapper.mdZip_swigregister
mdZip_swigregister(mdZip)

# This file is compatible with both classic and new-style classes.


